name: anj_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  fluttertoast: ^8.1.2
  geolocator: ^9.0.2
  get: 4.6.5
  get_storage: ^2.0.3
  image_picker: ^0.8.6+1
  intl: ^0.18.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/logos/
  uses-material-design: true
